package com.example.foodwaste.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.foodwaste.ui.InventoryViewModel

@Composable
fun AiRecipeScreen(vm: InventoryViewModel) {

    val food = vm.foodList.collectAsState().value.map { it.name.lowercase() }
    val allRecipes = vm.allRecipes

    var prompt by remember { mutableStateOf("") }

    var generated by remember { mutableStateOf<List<AiRecipeSuggestion>>(emptyList()) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {

        Text(
            text = "✨ AI Recipe Suggestions",
            style = MaterialTheme.typography.headlineSmall
        )

        Text(
            text = "We will recommend recipes based on:\n" +
                    "• Ingredients in your inventory\n" +
                    "• Your taste preference below",
            style = MaterialTheme.typography.bodyMedium
        )

        OutlinedTextField(
            value = prompt,
            onValueChange = { prompt = it },
            label = { Text("Tell AI what you feel like eating (e.g. spicy, light, high protein)...") },
            modifier = Modifier.fillMaxWidth(),
            minLines = 2
        )

        Button(
            onClick = {
                val result = allRecipes
                    .map { recipe ->
                        val owned = recipe.ingredients.count { it.lowercase() in food }
                        val missing = recipe.ingredients.size - owned

                        var score = owned * 2 - missing

                        val promptLower = prompt.lowercase()
                        if (promptLower.contains("spicy") && recipe.name.lowercase().contains("spicy")) {
                            score += 3
                        }
                        if (promptLower.contains("light") && recipe.name.lowercase().contains("salad")) {
                            score += 2
                        }

                        AiRecipeSuggestion(
                            name = recipe.name,
                            ingredients = recipe.ingredients,
                            missingCount = missing,
                            score = score
                        )
                    }
                    .sortedByDescending { it.score }
                    .take(10)
                generated = result
            },
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("Generate with AI (simulated)")
        }

        Divider()

        if (generated.isEmpty()) {
            Text(
                text = "No suggestions yet.\nEnter your preference and tap the button above.",
                style = MaterialTheme.typography.bodyMedium
            )
        } else {
            Text(
                text = "Recommended for you:",
                style = MaterialTheme.typography.titleMedium
            )

            LazyColumn(
                verticalArrangement = Arrangement.spacedBy(12.dp),
                modifier = Modifier.fillMaxSize()
            ) {
                items(generated) { item ->
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        colors = CardDefaults.cardColors(
                            containerColor = MaterialTheme.colorScheme.surfaceVariant
                        )
                    ) {
                        Column(Modifier.padding(16.dp)) {
                            Text(item.name, style = MaterialTheme.typography.titleMedium)
                            Text(
                                "Score: ${item.score}",
                                style = MaterialTheme.typography.bodySmall
                            )
                            Text(
                                "Missing ingredients: ${item.missingCount}",
                                style = MaterialTheme.typography.bodySmall
                            )
                            Text(
                                "All ingredients: ${item.ingredients.joinToString()}",
                                style = MaterialTheme.typography.bodySmall
                            )
                        }
                    }
                }
            }
        }
    }
}


data class AiRecipeSuggestion(
    val name: String,
    val ingredients: List<String>,
    val missingCount: Int,
    val score: Int
)

